### ISSUE TITLE
What is the license for this software?

### ISSUE THREAD

**Issue by justizin** [tmclaugh/suitcase#20]
Myself and some associates want to build upon this, possibly contribute back, but this is published with no license.

I don't really care exactly what license it's published under, I just want to make sure that I am legally deriving from it.

Thanks in advance!

J

**Comment by tmclaugh** [comment]
Total oversight on my part.  I've committed a copy of the MIT license in the LICENSE file.

I'm open to any and all changes to this to make it better.  I'd like to make this more flexible for others.  I'm really not against evaluating any idea. :)

**Comment by justizin** [comment]
Thanks!
